/* Autogenerated file. Do not edit manually. */
// could this be the issue?

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Position: (() => {
      const name = "Position";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Defence: (() => {
      const name = "Defence";
      return defineComponent(
        world,
        {
          plague: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Lifes: (() => {
      const name = "Lifes";
      return defineComponent(
        world,
        {
          count: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Name: (() => {
      const name = "Name";
      return defineComponent(
        world,
        {
          value: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Prosperity: (() => {
      const name = "Prosperity";
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    GameData: (() => {
      const name = "Prosperity";
      return defineComponent(
        world,
        {
          count_outposts: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    OutpostEntity: (() => {
      const name = "Prosperity";
      return defineComponent(
        world,
        {
          entity_id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Balance: (() => {
      const name = "Balance";
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    WorldEvent: (() => {
      const name = "WorldEvent";
      return defineComponent(
        world,
        {
          radius: RecsType.Number,
          event_type: RecsType.Number,
          block_number: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Game: (() => {
      const name = "Game";
      return defineComponent(
        world,
        {
          start_time: RecsType.Number,
          prize: RecsType.Number,
          status: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    GameTracker: (() => {
      const name = "GameTracker";
      return defineComponent(
        world,
        {
          count: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Ownership: (() => {
      const name = "Ownership";
      return defineComponent(
        world,
        {
          address: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),







    // this should not be here
    ClientCameraComponent: (() => {
      const name = "ClickCameraComp";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    // this should not be here
    ClickComponent: (() => {
      const name = "ClickCameraComp";
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

        // this should not be here
        OutpostState: (() => {
          const name = "OutpostState";
          return defineComponent(
            world,
            {
              state: RecsType.Number
            },
            {
              metadata: {
                name: name,
              },
            }
          );
        })(),
    




    AuthStatus: (() => {
      const name = "AuthStatus";
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    AuthRole: (() => {
      const name = "AuthRole";
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
